{
	"name"			: "Manajemen Barang",
	"version"		: "1.0.0",
	"depends"		: [ 
						"base",
						],
	"author"		: "Iqbal A",
	"category"		: "Management",
	"website"		: "http://www.vitraining.com",
	"description"	: "Sistem Manajemen Barang",
	"data"			: [
						"menu.xml",
						"security/ir.model.access.csv",
						"perangkat.xml",
						"power.xml",
						"lan.xml",
						"perangkatnondc.xml",
						"sop.xml",
						"bcp.xml",
						"berita.xml",
						"agenda.xml",
						"datauser.xml",
						"lokasi.xml",
						"subruang.xml",
						"merk.xml",
						"unit.xml",
						"subunit.xml",
						"kodeperangkat.xml",
						"kelompokperangkat.xml",
						"ruang.xml",
						"visit.xml",
					],
	"installable"	: True,
	"auto_install"	: False,
	"application"	: True,
	}